<<<<<<< HEAD
export const ALL_PRODUCT_REQUEST="ALL_PRODUCT_REQUEST";
export const ALL_PRODUCT_SUCCESS="ALL_PRODUCT_SUCCESS";
export const ALL_PRODUCT_FAIL="ALL_PRODUCT_FAIL";

export const PRODUCT_DETAILS_REQUEST="PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS="PRODUCT_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAIL=   "PRODUCT_DETAILS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
=======
export const ALL_PRRODUCT_REQUEST="ALL_PRODUCT_REQUEST";
export const ALL_PRRODUCT_SUCCESS="ALL_PRODUCT_SUCCESS";
export const ALL_PRRODUCT_FAIL="ALL_PRODUCT_REQUEST";
export const CLEAR = "CLEAR";
>>>>>>> 71d636c5c85ccb323282f8eba8e30437c8349eec
